CREATE TABLE custom_pool_report (
    report_date                 DATE,
    sr_no                       INTEGER,
    campaign_name               TEXT,
    phone                       TEXT,
    dnis                        TEXT,
    call_type                   TEXT,
    call_id                     TEXT,
    answered_hungup             TEXT,
    call_time                   TIMESTAMP,
    queue_id                    TEXT,
    queue_name                  TEXT,
    queue_wait_time             VARCHAR(12),
    total_wait_time             VARCHAR(12),
    hangup_details              TEXT,
    customer_hold_time          VARCHAR(12),
    actual_channel              TEXT,
    user_name                   TEXT,
    user_id                     TEXT,
    user_setup_time             VARCHAR(12),
    user_ringing_time           VARCHAR(12),
    user_talk_time              VARCHAR(12),
    cumulative_user_talk_time   VARCHAR(12),
    wrap_time                   VARCHAR(12),
    user_disposition_code       TEXT,
    main_menu_input             TEXT
);